#include "mort/cpu/op_t.h"

static Op_t ops[] = {
  {
    .code = 0x00,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'nop',
  },
  {
    .code = 0x01,
    .cycles = {
        .jump = 0,
        .next = 12,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 3,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x02,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x03,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'inc',
  },
  {
    .code = 0x04,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'inc',
  },
  {
    .code = 0x05,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'dec',
  },
  {
    .code = 0x06,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x07,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '0',
      .n = '0',
      .h = '0',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'rlca',
  },
  {
    .code = 0x08,
    .cycles = {
        .jump = 0,
        .next = 20,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 3,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x09,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'add',
  },
  {
    .code = 0x0A,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x0B,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'dec',
  },
  {
    .code = 0x0C,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'inc',
  },
  {
    .code = 0x0D,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'dec',
  },
  {
    .code = 0x0E,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x0F,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '0',
      .n = '0',
      .h = '0',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'rrca',
  },
  {
    .code = 0x10,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'stop',
  },
  {
    .code = 0x11,
    .cycles = {
        .jump = 0,
        .next = 12,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 3,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x12,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x13,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'inc',
  },
  {
    .code = 0x14,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'inc',
  },
  {
    .code = 0x15,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'dec',
  },
  {
    .code = 0x16,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x17,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '0',
      .n = '0',
      .h = '0',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'rla',
  },
  {
    .code = 0x18,
    .cycles = {
        .jump = 0,
        .next = 12,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'jr',
  },
  {
    .code = 0x19,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'add',
  },
  {
    .code = 0x1A,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x1B,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'dec',
  },
  {
    .code = 0x1C,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'inc',
  },
  {
    .code = 0x1D,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'dec',
  },
  {
    .code = 0x1E,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x1F,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '0',
      .n = '0',
      .h = '0',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'rra',
  },
  {
    .code = 0x20,
    .cycles = {
      .jump = 12
      .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'jr',
  },
  {
    .code = 0x21,
    .cycles = {
        .jump = 0,
        .next = 12,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 3,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x22,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x23,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'inc',
  },
  {
    .code = 0x24,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'inc',
  },
  {
    .code = 0x25,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'dec',
  },
  {
    .code = 0x26,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x27,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '-',
      .h = '0',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'daa',
  },
  {
    .code = 0x28,
    .cycles = {
      .jump = 12
      .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'jr',
  },
  {
    .code = 0x29,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'add',
  },
  {
    .code = 0x2A,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x2B,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'dec',
  },
  {
    .code = 0x2C,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'inc',
  },
  {
    .code = 0x2D,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'dec',
  },
  {
    .code = 0x2E,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x2F,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '1',
      .h = '1',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'cpl',
  },
  {
    .code = 0x30,
    .cycles = {
      .jump = 12
      .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'jr',
  },
  {
    .code = 0x31,
    .cycles = {
        .jump = 0,
        .next = 12,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 3,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x32,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x33,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'inc',
  },
  {
    .code = 0x34,
    .cycles = {
        .jump = 0,
        .next = 12,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'inc',
  },
  {
    .code = 0x35,
    .cycles = {
        .jump = 0,
        .next = 12,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'dec',
  },
  {
    .code = 0x36,
    .cycles = {
        .jump = 0,
        .next = 12,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x37,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '0',
      .h = '0',
      .c = '1',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'scf',
  },
  {
    .code = 0x38,
    .cycles = {
      .jump = 12
      .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'jr',
  },
  {
    .code = 0x39,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'add',
  },
  {
    .code = 0x3A,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x3B,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'dec',
  },
  {
    .code = 0x3C,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'inc',
  },
  {
    .code = 0x3D,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'dec',
  },
  {
    .code = 0x3E,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x3F,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '0',
      .h = '0',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ccf',
  },
  {
    .code = 0x40,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x41,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x42,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x43,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x44,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x45,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x46,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x47,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x48,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x49,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x4A,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x4B,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x4C,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x4D,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x4E,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x4F,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x50,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x51,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x52,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x53,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x54,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x55,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x56,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x57,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x58,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x59,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x5A,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x5B,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x5C,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x5D,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x5E,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x5F,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x60,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x61,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x62,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x63,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x64,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x65,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x66,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x67,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x68,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x69,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x6A,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x6B,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x6C,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x6D,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x6E,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x6F,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x70,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x71,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x72,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x73,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x74,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x75,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x76,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'halt',
  },
  {
    .code = 0x77,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x78,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x79,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x7A,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x7B,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x7C,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x7D,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x7E,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x7F,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0x80,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'add',
  },
  {
    .code = 0x81,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'add',
  },
  {
    .code = 0x82,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'add',
  },
  {
    .code = 0x83,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'add',
  },
  {
    .code = 0x84,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'add',
  },
  {
    .code = 0x85,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'add',
  },
  {
    .code = 0x86,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'add',
  },
  {
    .code = 0x87,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'add',
  },
  {
    .code = 0x88,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'adc',
  },
  {
    .code = 0x89,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'adc',
  },
  {
    .code = 0x8A,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'adc',
  },
  {
    .code = 0x8B,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'adc',
  },
  {
    .code = 0x8C,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'adc',
  },
  {
    .code = 0x8D,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'adc',
  },
  {
    .code = 0x8E,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'adc',
  },
  {
    .code = 0x8F,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'adc',
  },
  {
    .code = 0x90,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'sub',
  },
  {
    .code = 0x91,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'sub',
  },
  {
    .code = 0x92,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'sub',
  },
  {
    .code = 0x93,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'sub',
  },
  {
    .code = 0x94,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'sub',
  },
  {
    .code = 0x95,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'sub',
  },
  {
    .code = 0x96,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'sub',
  },
  {
    .code = 0x97,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '1',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'sub',
  },
  {
    .code = 0x98,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'sbc',
  },
  {
    .code = 0x99,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'sbc',
  },
  {
    .code = 0x9A,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'sbc',
  },
  {
    .code = 0x9B,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'sbc',
  },
  {
    .code = 0x9C,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'sbc',
  },
  {
    .code = 0x9D,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'sbc',
  },
  {
    .code = 0x9E,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'sbc',
  },
  {
    .code = 0x9F,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'sbc',
  },
  {
    .code = 0xA0,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '1',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'and',
  },
  {
    .code = 0xA1,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '1',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'and',
  },
  {
    .code = 0xA2,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '1',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'and',
  },
  {
    .code = 0xA3,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '1',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'and',
  },
  {
    .code = 0xA4,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '1',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'and',
  },
  {
    .code = 0xA5,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '1',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'and',
  },
  {
    .code = 0xA6,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '1',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'and',
  },
  {
    .code = 0xA7,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '1',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'and',
  },
  {
    .code = 0xA8,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '0',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'xor',
  },
  {
    .code = 0xA9,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '0',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'xor',
  },
  {
    .code = 0xAA,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '0',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'xor',
  },
  {
    .code = 0xAB,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '0',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'xor',
  },
  {
    .code = 0xAC,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '0',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'xor',
  },
  {
    .code = 0xAD,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '0',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'xor',
  },
  {
    .code = 0xAE,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '0',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'xor',
  },
  {
    .code = 0xAF,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '1',
      .n = '0',
      .h = '0',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'xor',
  },
  {
    .code = 0xB0,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '0',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'or',
  },
  {
    .code = 0xB1,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '0',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'or',
  },
  {
    .code = 0xB2,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '0',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'or',
  },
  {
    .code = 0xB3,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '0',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'or',
  },
  {
    .code = 0xB4,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '0',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'or',
  },
  {
    .code = 0xB5,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '0',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'or',
  },
  {
    .code = 0xB6,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '0',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'or',
  },
  {
    .code = 0xB7,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '0',
      .c = '0',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'or',
  },
  {
    .code = 0xB8,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'cp',
  },
  {
    .code = 0xB9,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'cp',
  },
  {
    .code = 0xBA,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'cp',
  },
  {
    .code = 0xBB,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'cp',
  },
  {
    .code = 0xBC,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'cp',
  },
  {
    .code = 0xBD,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'cp',
  },
  {
    .code = 0xBE,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'cp',
  },
  {
    .code = 0xBF,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '1',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'cp',
  },
  {
    .code = 0xC0,
    .cycles = {
      .jump = 20
      .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ret',
  },
  {
    .code = 0xC1,
    .cycles = {
        .jump = 0,
        .next = 12,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'pop',
  },
  {
    .code = 0xC2,
    .cycles = {
      .jump = 16
      .next = 12,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 3,
    .method = NULL,
    .mnemonic = 'jp',
  },
  {
    .code = 0xC3,
    .cycles = {
        .jump = 0,
        .next = 16,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 3,
    .method = NULL,
    .mnemonic = 'jp',
  },
  {
    .code = 0xC4,
    .cycles = {
      .jump = 24
      .next = 12,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 3,
    .method = NULL,
    .mnemonic = 'call',
  },
  {
    .code = 0xC5,
    .cycles = {
        .jump = 0,
        .next = 16,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'push',
  },
  {
    .code = 0xC6,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'add',
  },
  {
    .code = 0xC7,
    .cycles = {
        .jump = 0,
        .next = 16,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'rst',
  },
  {
    .code = 0xC8,
    .cycles = {
      .jump = 20
      .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ret',
  },
  {
    .code = 0xC9,
    .cycles = {
        .jump = 0,
        .next = 16,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ret',
  },
  {
    .code = 0xCA,
    .cycles = {
      .jump = 16
      .next = 12,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 3,
    .method = NULL,
    .mnemonic = 'jp',
  },
  {
    .code = 0xCB,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'prefix',
  },
  {
    .code = 0xCC,
    .cycles = {
      .jump = 24
      .next = 12,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 3,
    .method = NULL,
    .mnemonic = 'call',
  },
  {
    .code = 0xCD,
    .cycles = {
        .jump = 0,
        .next = 24,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 3,
    .method = NULL,
    .mnemonic = 'call',
  },
  {
    .code = 0xCE,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'adc',
  },
  {
    .code = 0xCF,
    .cycles = {
        .jump = 0,
        .next = 16,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'rst',
  },
  {
    .code = 0xD0,
    .cycles = {
      .jump = 20
      .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ret',
  },
  {
    .code = 0xD1,
    .cycles = {
        .jump = 0,
        .next = 12,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'pop',
  },
  {
    .code = 0xD2,
    .cycles = {
      .jump = 16
      .next = 12,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 3,
    .method = NULL,
    .mnemonic = 'jp',
  },
  {
    .code = 0xD3,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'illegal_d3',
  },
  {
    .code = 0xD4,
    .cycles = {
      .jump = 24
      .next = 12,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 3,
    .method = NULL,
    .mnemonic = 'call',
  },
  {
    .code = 0xD5,
    .cycles = {
        .jump = 0,
        .next = 16,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'push',
  },
  {
    .code = 0xD6,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'sub',
  },
  {
    .code = 0xD7,
    .cycles = {
        .jump = 0,
        .next = 16,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'rst',
  },
  {
    .code = 0xD8,
    .cycles = {
      .jump = 20
      .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ret',
  },
  {
    .code = 0xD9,
    .cycles = {
        .jump = 0,
        .next = 16,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'reti',
  },
  {
    .code = 0xDA,
    .cycles = {
      .jump = 16
      .next = 12,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 3,
    .method = NULL,
    .mnemonic = 'jp',
  },
  {
    .code = 0xDB,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'illegal_db',
  },
  {
    .code = 0xDC,
    .cycles = {
      .jump = 24
      .next = 12,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 3,
    .method = NULL,
    .mnemonic = 'call',
  },
  {
    .code = 0xDD,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'illegal_dd',
  },
  {
    .code = 0xDE,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'sbc',
  },
  {
    .code = 0xDF,
    .cycles = {
        .jump = 0,
        .next = 16,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'rst',
  },
  {
    .code = 0xE0,
    .cycles = {
        .jump = 0,
        .next = 12,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'ldh',
  },
  {
    .code = 0xE1,
    .cycles = {
        .jump = 0,
        .next = 12,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'pop',
  },
  {
    .code = 0xE2,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0xE3,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'illegal_e3',
  },
  {
    .code = 0xE4,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'illegal_e4',
  },
  {
    .code = 0xE5,
    .cycles = {
        .jump = 0,
        .next = 16,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'push',
  },
  {
    .code = 0xE6,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '1',
      .c = '0',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'and',
  },
  {
    .code = 0xE7,
    .cycles = {
        .jump = 0,
        .next = 16,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'rst',
  },
  {
    .code = 0xE8,
    .cycles = {
        .jump = 0,
        .next = 16,
    },
    .flags = {
      .z = '0',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'add',
  },
  {
    .code = 0xE9,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'jp',
  },
  {
    .code = 0xEA,
    .cycles = {
        .jump = 0,
        .next = 16,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 3,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0xEB,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'illegal_eb',
  },
  {
    .code = 0xEC,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'illegal_ec',
  },
  {
    .code = 0xED,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'illegal_ed',
  },
  {
    .code = 0xEE,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '0',
      .c = '0',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'xor',
  },
  {
    .code = 0xEF,
    .cycles = {
        .jump = 0,
        .next = 16,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'rst',
  },
  {
    .code = 0xF0,
    .cycles = {
        .jump = 0,
        .next = 12,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'ldh',
  },
  {
    .code = 0xF1,
    .cycles = {
        .jump = 0,
        .next = 12,
    },
    .flags = {
      .z = 'Z',
      .n = 'N',
      .h = 'H',
      .c = 'C',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'pop',
  },
  {
    .code = 0xF2,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0xF3,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'di',
  },
  {
    .code = 0xF4,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'illegal_f4',
  },
  {
    .code = 0xF5,
    .cycles = {
        .jump = 0,
        .next = 16,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'push',
  },
  {
    .code = 0xF6,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = 'Z',
      .n = '0',
      .h = '0',
      .c = '0',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'or',
  },
  {
    .code = 0xF7,
    .cycles = {
        .jump = 0,
        .next = 16,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'rst',
  },
  {
    .code = 0xF8,
    .cycles = {
        .jump = 0,
        .next = 12,
    },
    .flags = {
      .z = '0',
      .n = '0',
      .h = 'H',
      .c = 'C',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0xF9,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0xFA,
    .cycles = {
        .jump = 0,
        .next = 16,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 3,
    .method = NULL,
    .mnemonic = 'ld',
  },
  {
    .code = 0xFB,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'ei',
  },
  {
    .code = 0xFC,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'illegal_fc',
  },
  {
    .code = 0xFD,
    .cycles = {
        .jump = 0,
        .next = 4,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'illegal_fd',
  },
  {
    .code = 0xFE,
    .cycles = {
        .jump = 0,
        .next = 8,
    },
    .flags = {
      .z = 'Z',
      .n = '1',
      .h = 'H',
      .c = 'C',
    },
    .length = 2,
    .method = NULL,
    .mnemonic = 'cp',
  },
  {
    .code = 0xFF,
    .cycles = {
        .jump = 0,
        .next = 16,
    },
    .flags = {
      .z = '-',
      .n = '-',
      .h = '-',
      .c = '-',
    },
    .length = 1,
    .method = NULL,
    .mnemonic = 'rst',
  },
};

inline Op_t *GetOp(uint16_t opcode) {
  return &ops[opcode];
}
